/**
 * This file was generated by the JPA Modeler
 */
package Entidades;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.xml.bind.annotation.*;

/**
 * @author Windows XP
 */
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
@NamedQueries({
    @NamedQuery(name = "Carrera.findAll", query = "Select e from Carrera e"),
    @NamedQuery(name = "Carrera.findByNombre", query = "Select c from Carrera c where c.nombre=:nombre")})
public class Carrera implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long codigo;

    @Basic
    private String nombre;

    @XmlTransient
    @OneToMany(targetEntity = Asignatura_Carrera.class, mappedBy = "carrera")
    private List<Asignatura_Carrera> asignatura_Carreras;

    @XmlTransient
    @ManyToMany(targetEntity = Usuario.class, mappedBy = "carreras")
    private List<Usuario> usuarios;

    @ManyToMany(targetEntity = Periodo_Examen.class)
    private List<Periodo_Examen> periodos_Examenes;

    @ManyToMany(targetEntity = Asignatura.class)
    private List<Asignatura> asignaturas;

    public Carrera(Long codigo, String nombre) {
        this.codigo = codigo;
        this.nombre = nombre;
    }

    public Carrera() {
    }

    public Long getCodigo() {
        return this.codigo;
    }

    public void setCodigo(Long codigo) {
        this.codigo = codigo;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public List<Asignatura_Carrera> getAsignatura_Carreras() {
        return this.asignatura_Carreras;
    }

    public void setAsignatura_Carreras(List<Asignatura_Carrera> asignatura_Carreras) {
        this.asignatura_Carreras = asignatura_Carreras;
    }

    public List<Usuario> getUsuarios() {
        return this.usuarios;
    }

    public void setUsuarios(List<Usuario> usuarios) {
        this.usuarios = usuarios;
    }

    public List<Periodo_Examen> getPeriodos_Examenes() {
        return this.periodos_Examenes;
    }

    public void setPeriodos_Examenes(List<Periodo_Examen> periodos_Examenes) {
        this.periodos_Examenes = periodos_Examenes;
    }

    public List<Asignatura> getAsignaturas() {
        return this.asignaturas;
    }

    public void setAsignaturas(List<Asignatura> asignaturas) {
        this.asignaturas = asignaturas;
    }

}
