/**
 * This file was generated by the JPA Modeler
 */
package Entidades;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.xml.bind.annotation.*;

/**
 * @author Windows XP
 */
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
@NamedQueries({
    @NamedQuery(name = "Usuario.findAll", query = "Select e from Usuario e"),
    @NamedQuery(name = "Usuario.findByNombre", query = "Select u from Usuario u where u.nombre=:nombre"),
    @NamedQuery(name = "Usuario.findByApellido", query = "Select u from Usuario u where u.apellido=:apellido"),
    @NamedQuery(name = "Usuario.findByEmail", query = "Select u from Usuario u where u.email=:email"),
    @NamedQuery(name = "Usuario.findByPassword", query = "Select u from Usuario u where u.password=:password")})
public class Usuario implements Serializable {

    @Column(unique = true)
    @Id
    private String cedula;

    @Basic
    private String nombre;

    @Basic
    private String apellido;

    @Basic
    private String email;

    @Basic
    private String password;

    @XmlTransient
    @OneToMany(targetEntity = Estudiante_Examen.class, mappedBy = "usuario")
    private List<Estudiante_Examen> calificacionesExamenes;

    @XmlTransient
    @OneToMany(targetEntity = Estudiante_Curso.class, mappedBy = "usuario")
    private List<Estudiante_Curso> calificacionesCursos;

    @ManyToMany(targetEntity = Rol.class)
    private List<Rol> roles;

    @ManyToMany(targetEntity = Carrera.class)
    private List<Carrera> carreras;

    @ManyToMany(targetEntity = Examen.class)
    private List<Examen> inscripcionesExamenes;

    @ManyToMany(targetEntity = Curso.class)
    private List<Curso> cursoes;

    public Usuario(String cedula, String nombre, String apellido, String email, String password) {
        this.cedula = cedula;
        this.nombre = nombre;
        this.apellido = apellido;
        this.email = email;
        this.password = password;
    }

    public Usuario() {
    }

    public String getCedula() {
        return this.cedula;
    }

    public void setCedula(String cedula) {
        this.cedula = cedula;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellido() {
        return this.apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public List<Estudiante_Examen> getCalificacionesExamenes() {
        return this.calificacionesExamenes;
    }

    public void setCalificacionesExamenes(List<Estudiante_Examen> calificacionesExamenes) {
        this.calificacionesExamenes = calificacionesExamenes;
    }

    public List<Estudiante_Curso> getCalificacionesCursos() {
        return this.calificacionesCursos;
    }

    public void setCalificacionesCursos(List<Estudiante_Curso> calificacionesCursos) {
        this.calificacionesCursos = calificacionesCursos;
    }

    public List<Rol> getRoles() {
        return this.roles;
    }

    public void setRoles(List<Rol> roles) {
        this.roles = roles;
    }

    public List<Carrera> getCarreras() {
        return this.carreras;
    }

    public void setCarreras(List<Carrera> carreras) {
        this.carreras = carreras;
    }

    public List<Examen> getInscripcionesExamenes() {
        return this.inscripcionesExamenes;
    }

    public void setInscripcionesExamenes(List<Examen> inscripcionesExamenes) {
        this.inscripcionesExamenes = inscripcionesExamenes;
    }

    public List<Curso> getCursoes() {
        return this.cursoes;
    }

    public void setCursoes(List<Curso> cursoes) {
        this.cursoes = cursoes;
    }

}
