/**
 * This file was generated by the JPA Modeler
 */
package com.miudelar.server.logic.datatypes;

import java.io.Serializable;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Objects;


public class DtCursoAng implements Serializable {

    private Long id;

    private String fecha;

    private DtAsignatura_Carrera asignatura_Carrera;

    private List<DtHorario> horarios;

    private List<DtEstudiante_Curso> cursos;

    private List<DtUsuario> inscriptos;

    public DtCursoAng(Long id, Date fecha, DtAsignatura_Carrera asignatura_Carrera, List<DtHorario> horarios) {
        this.id = id;
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String date = dateFormat.format(fecha);
        this.fecha = date;
        this.asignatura_Carrera = asignatura_Carrera;
        this.horarios = horarios;
    }
    
    public DtCursoAng(Date fecha, DtAsignatura_Carrera asignatura_Carrera) {
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String date = dateFormat.format(fecha);
        this.fecha = date;
        this.asignatura_Carrera = asignatura_Carrera;
    }
        
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFecha() {
        return fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    public DtAsignatura_Carrera getAsignatura_Carrera() {
        return asignatura_Carrera;
    }

    public void setAsignatura_Carrera(DtAsignatura_Carrera asignatura_Carrera) {
        this.asignatura_Carrera = asignatura_Carrera;
    }
    
    

    public List<DtHorario> getHorarios() {
        return this.horarios;
    }

    public void setHorarios(List<DtHorario> horarios) {
        this.horarios = horarios;
    }

    public List<DtEstudiante_Curso> getCursos() {
        return this.cursos;
    }

    public void setCursos(List<DtEstudiante_Curso> cursos) {
        this.cursos = cursos;
    }

    public List<DtUsuario> getInscriptos() {
        return this.inscriptos;
    }

    public void setInscriptos(List<DtUsuario> inscriptos) {
        this.inscriptos = inscriptos;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 41 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final DtCursoAng other = (DtCursoAng) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }

    
}
