/**
 * This file was generated by the JPA Modeler
 */
package com.miudelar.server.logic.datatypes;

import java.io.Serializable;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Objects;


public class DtExamenAng implements Serializable {

    private Long id;

    private String fecha;

    private DtAsignatura_Carrera asignatura_Carrera;

    private List<DtEstudiante_Examen> examenes;

    private List<DtUsuario> inscriptos;

    public DtExamenAng(Long id, Date fecha) {
        this.id = id;
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String date = dateFormat.format(fecha);
        this.fecha = date;
    }

    public DtExamenAng(Long id, Date fecha, DtAsignatura_Carrera asignatura_Carrera) {
        this.id = id;
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String date = dateFormat.format(fecha);
        this.fecha = date;
        this.asignatura_Carrera = asignatura_Carrera;
    }
    

    public DtExamenAng() {
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFecha() {
        return this.fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    public DtAsignatura_Carrera getAsignatura_Carrera() {
        return this.asignatura_Carrera;
    }

    public void setAsignatura_Carrera(DtAsignatura_Carrera asignatura_Carrera) {
        this.asignatura_Carrera = asignatura_Carrera;
    }

    public List<DtEstudiante_Examen> getExamenes() {
        return this.examenes;
    }

    public void setExamenes(List<DtEstudiante_Examen> examenes) {
        this.examenes = examenes;
    }

    public List<DtUsuario> getInscriptos() {
        return this.inscriptos;
    }

    public void setInscriptos(List<DtUsuario> inscriptos) {
        this.inscriptos = inscriptos;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 29 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final DtExamenAng other = (DtExamenAng) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }
    
    

}
