/**
 * This file was generated by the JPA Modeler
 */
package com.miudelar.server.logic.datatypes;

import java.io.Serializable;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class DtUsuario implements Serializable {

    private String cedula;

    private String nombre;

    private String apellido;

    private String email;

    private String password;

    private List<DtEstudiante_Examen> examenes;

    private List<DtEstudiante_Curso> cursos;

    private List<DtRol> roles;

    private List<DtCarrera> carreras;


    public DtUsuario(String cedula, String nombre, String apellido, String email, String password, List<DtRol> roles) {
        this.cedula = cedula;
        this.nombre = nombre;
        this.apellido = apellido;
        this.email = email;
        this.password = password;
        this.roles = roles;
    }
    
    public DtUsuario(String cedula, String nombre, String apellido, String email, List<DtCarrera> carreras) {
        this.cedula = cedula;
        this.nombre = nombre;
        this.apellido = apellido;
        this.email = email;
        this.carreras = carreras;
    }
    
 
    public DtUsuario(String cedula, String nombre, String apellido, String email, String password) {
        this.cedula = cedula;
        this.nombre = nombre;
        this.apellido = apellido;
        this.email = email;
        this.password = password;
    }

    public DtUsuario() {
    }

    public String getCedula() {
        return this.cedula;
    }

    public void setCedula(String cedula) {
        this.cedula = cedula;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellido() {
        return this.apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public List<DtEstudiante_Examen> getExamenes() {
        return this.examenes;
    }

    public void setExamenes(List<DtEstudiante_Examen> examenes) {
        this.examenes = examenes;
    }

    public List<DtEstudiante_Curso> getCursos() {
        return this.cursos;
    }

    public List<DtRol> getRoles() {
        return this.roles;
    }

    public void setRoles(List<DtRol> roles) {
        this.roles = roles;
    }

    public List<DtCarrera> getCarreras() {
        return this.carreras;
    }

    public void setCarreras(List<DtCarrera> carreras) {
        this.carreras = carreras;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 47 * hash + Objects.hashCode(this.cedula);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final DtUsuario other = (DtUsuario) obj;
        if (!Objects.equals(this.cedula, other.cedula)) {
            return false;
        }
        return true;
    }
  
}
